#! /bin/sh
#
# GCC binary package post-install script

cd PREFIX
echo "Running postinstall at PREFIX" >install.log
make ins-fixup                                          \
     prefix=PREFIX                                      \
     machine=MACHINE                                    \
     version=VERSION                                    \
     built_prefix=BUILT_PREFIX 2>&1 >>install.log
